apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-22
spec:
  selector:
    matchLabels:
      app: app-22
  template:
    metadata:
      labels:
        app: app-22
    spec:
      volumes:
        - name: app-22
          persistentVolumeClaim:
            claimName: local-pvc
      containers:
        - name: busybox
          image: busybox
          command:
            [
              "sh",
              "-c",
              "while true; do echo `date` 'Test from busybox' >> /app-22/test.txt; sleep 5; done",
            ]
          volumeMounts:
            - mountPath: /app-22
              name: app-22
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: multitool
          image: wbitt/network-multitool:latest
          env:
            - name: HTTP_PORT
              value: "1180"
            - name: HTTPS_PORT
              value: "11443"
          volumeMounts:
            - mountPath: /app
              name: app-22
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
