apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-22-nfs
spec:
  selector:
    matchLabels:
      app: app-22-nfs
  template:
    metadata:
      labels:
        app: app-22-nfs
    spec:
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
      containers:
        - name: multitool
          image: wbitt/network-multitool:latest
          env:
            - name: HTTP_PORT
              value: "1180"
            - name: HTTPS_PORT
              value: "11443"
          volumeMounts:
            - mountPath: /app
              name: nfs-storage
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
