---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos_7
    # image: quay.io/centos/centos:7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    privileged: true
  - name: centos_8
    image: docker.io/pycontribs/centos:8
    # image: centos:8
    pre_build_image: true
    privileged: true
  - name: oraclelinux8
    # image: quay.io/centos/centos:8
    image: oraclelinux:8
    pre_build_image: true
    privileged: true
  - name: ubuntu
    # image: quay.io/centos/centos:8
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
  options:
    sudo: true
