---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: oraclelinux8
    image: oraclelinux:8
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
