---
- name: Install sudo packages
  # become: true
  ansible.builtin.yum:
    name: sudo
- name: Install sudo packages
  # become: true
  ansible.builtin.yum:
    name: git
# tasks file for lighthouse-role
- name: Lighthouse download
  # become: true
  # become_user: nginx
  ansible.builtin.git:
    repo: "{{ lighthouse_repo }}"
    version: master
    dest: "{{ lighthouse_dest_dir }}"
# use default dir  /usr/share/nginx/html or create your config
# - name: Create config Lighthouse
#   become: true
#   ansible.builtin.template:
#     src: lighthouse.j2
#     dest: /etc/nginx/conf.d/default.conf
#     mode: "0644"
#   notify: Reload nginx service
