apiVersion: v1
kind: Pod
metadata:
  name: multitool-test
spec:
  containers:
    - name: multitool-test
      image: wbitt/network-multitool:latest
      ports:
        - containerPort: 8080
      command: ["/bin/sh", "-c", 'echo "Hello, Kubernetes!" && sleep 3600']
