apiVersion: v1
kind: Service
metadata:
  name: srv-app14-node
spec:
  type: NodePort
  selector:
    app: app-1.4
  ports:
    - name: nginx-port
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30001
    - name: multitool-port
      protocol: TCP
      port: 9002
      targetPort: 1180
      nodePort: 30002
