apiVersion: v1
kind: Service
metadata:
  name: srv-app14
spec:
  selector:
    app: app-1.4
  ports:
    - name: nginx-port
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool-port-http
      protocol: TCP
      port: 9002
      targetPort: 1180
