apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-user
  namespace: default
subjects:
  - kind: User
    name: log-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: log-user
  apiGroup: rbac.authorization.k8s.io
