apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-13
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1.3
  template:
    metadata:
      labels:
        app: app-1.3
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
              name: nginx-port
        - name: multitool
          image: wbitt/network-multitool:latest
          env:
            - name: HTTP_PORT
              value: "1180"
            - name: HTTPS_PORT
              value: "11443"
          ports:
            - containerPort: 1180
              name: http-port
            - containerPort: 11443
              name: https-port
