apiVersion: v1
kind: Pod
metadata:
  name: multitool-test
spec:
  containers:
    - name: multitool-test
      image: wbitt/network-multitool:latest
      ports:
        - containerPort: 8080
      command: ["/bin/sh", "-c"]
      args:
        - "sleep 3600"
