apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: nginx-pre
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nslookup srv-nginx.default.svc.cluster.local; do echo waiting for srv-nginx; sleep 2; done;",
            ]
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
