apiVersion: v1
kind: Service
metadata:
  name: srv-app13
spec:
  selector:
    app: app-1.3
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80
    - name: multitool-port-http
      protocol: TCP
      port: 8080
      targetPort: 1180
